Document: fdenavi
Title: Debian fdenavi Manual
Author: <insert document author here>
Abstract: This manual describes what fdenavi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fdenavi/fdenavi.sgml.gz

Format: postscript
Files: /usr/share/doc/fdenavi/fdenavi.ps.gz

Format: text
Files: /usr/share/doc/fdenavi/fdenavi.text.gz

Format: HTML
Index: /usr/share/doc/fdenavi/html/index.html
Files: /usr/share/doc/fdenavi/html/*.html
